library(dplyr)
library(ggplot2)
sccPM25 <- readRDS("/home/biffster/Dropbox/Work/Training/Data science/Coursera/Exploratory Data Analysis/summarySCC_PM25.rds")
yearsTypeBaltimore <- group_by(sccPM25[which(sccPM25$fips == 24510),], year, type)
plotthis <- summarise(yearsTypeBaltimore, count=sum(Emissions))
g <- ggplot(plotthis, aes(year,count), color=type)
g <- g + geom_point() + facet_grid(. ~ type) + geom_smooth(method="lm")
print(g)
dev.copy(png,"project2_plot3.png")
dev.off()
